version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    tty: true
    networks: 
      main:
    volumes:
      - .:/app
  mysql:
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ssa-base
      MYSQL_ROOT_PASSWORD: ssa-pass
      MYSQL_USER: ssa-tor
      MYSQL_PASSWORD: ssa-pass
    command: --default-authentication-plugin=mysql_native_password
    networks: 
      main:
networks: 
  main:
